sudo: required
services:
  - docker

before_install:
  - docker build -t rp199/multi-docker-fibonnaci-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rp199/multi-docker-fibonnaci-client-test npm test

after_success:
  - docker build -t rp199/multi-docker-fibonnaci-client ./client
  - docker build -t rp199/multi-docker-fibonnaci-nginx ./nginx
  - docker build -t rp199/multi-docker-fibonnaci-server ./server
  - docker build -t rp199/multi-docker-fibonnaci-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rp199/multi-docker-fibonnaci-client
  - docker push rp199/multi-docker-fibonnaci-nginx
  - docker push rp199/multi-docker-fibonnaci-server
  - docker push rp199/multi-docker-fibonnaci-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker-fibonnaci
  env: MultiDockerFibonnaci-env
  bucket_name: elasticbeanstalk-eu-west-1-291530085812
  bucket_path: multi-docker-fibonnaci
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
